server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commute
    username: postgres
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    
      